# Generated by Django 3.0.3 on 2020-03-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0002_ingresso_pessoa_pessoafisica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='data_icinio',
        ),
        migrations.RemoveField(
            model_name='ingresso',
            name='realizador',
        ),
        migrations.RemoveField(
            model_name='ingresso',
            name='sigla',
        ),
    ]
