# Generated by Django 3.0.3 on 2020-03-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0003_auto_20200313_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Ingresso',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='pessoa_ptr',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
    ]
