# Generated by Django 3.0.3 on 2020-03-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0005_auto_20200313_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(blank=True, help_text='Número do cpf no formato 00000000000', max_length=15, null=True, verbose_name='CPF'),
        ),
    ]
