# Generated by Django 3.0.3 on 2020-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0006_auto_20200313_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='descricao',
            field=models.CharField(max_length=128, verbose_name='nome'),
        ),
    ]
